In [1]:

!pip install tensorflow-gpu==2.0.0

     |████████████████████████████████| 380.8MB 41kB/s 
     |████████████████████████████████| 3.8MB 48.0MB/s 
     |████████████████████████████████| 450kB 33.0MB/s 
  Created wheel for gast: filename=gast-0.2.2-cp36-none-any.whl size=7540 sha256=3c7d86237de2aa066a6e84d4bdd610fb5354470972be1d996afde5625dd7139e
  Stored in directory: /root/.cache/pip/wheels/5c/2e/7e/a1d4d4fcebe6c381f378ce7743a3ced3699feb89bcfbdadadd
Successfully built gast
ERROR: tensorflow 2.2.0 has requirement gast==0.3.3, but you'll have gast 0.2.2 which is incompatible.
ERROR: tensorflow 2.2.0 has requirement tensorboard<2.3.0,>=2.2.0, but you'll have tensorboard 2.0.2 which is incompatible.
ERROR: tensorflow 2.2.0 has requirement tensorflow-estimator<2.3.0,>=2.2.0, but you'll have tensorflow-estimator 2.0.1 which is incompatible.
ERROR: tensorflow-probability 0.10.0rc0 has requirement gast>=0.3.2, but you'll have gast 0.2.2 which is incompatible.
  Found existing installation: tensorboard 2.2.1
    Uninstalling t

In [0]:
import tensorflow as tf
import numpy as np

In [3]:
tf.__version__

'2.0.0'

In [0]:
tensor_20 = tf.constant([[23,4],[32,51]])

In [33]:
tensor_20

<tf.Tensor: id=28, shape=(2, 2), dtype=int32, numpy=
array([[23,  4],
       [32, 51]], dtype=int32)>

In [34]:
tensor_20.shape

TensorShape([2, 2])

In [24]:
tensor_20.numpy()

array([[23,  4],
       [32, 21]], dtype=int32)

In [0]:
numpy_tensor=np.array([[45,6], [36,7]])

In [0]:
tensor_from_numpy=tf.constant(numpy_tensor)

In [10]:
tensor_from_numpy

<tf.Tensor: id=1, shape=(2, 2), dtype=int64, numpy=
array([[45,  6],
       [36,  7]])>

#Variable
defining a variable

In [11]:
tf2_variable=tf.Variable([[1.,2.,3.], [4.,5.,6.]])
tf2_variable

<tf.Variable 'Variable:0' shape=(2, 3) dtype=float32, numpy=
array([[1., 2., 3.],
       [4., 5., 6.]], dtype=float32)>

getting the values of a variable

In [12]:
tf2_variable.numpy()

array([[1., 2., 3.],
       [4., 5., 6.]], dtype=float32)

In [13]:
tf2_variable.shape

TensorShape([2, 3])

change specific value in variable

In [14]:
tf2_variable[0,2].assign(100)

<tf.Variable 'UnreadVariable' shape=(2, 3) dtype=float32, numpy=
array([[  1.,   2., 100.],
       [  4.,   5.,   6.]], dtype=float32)>

In [15]:
tf2_variable

<tf.Variable 'Variable:0' shape=(2, 3) dtype=float32, numpy=
array([[  1.,   2., 100.],
       [  4.,   5.,   6.]], dtype=float32)>

# operations with tensorflow

In [16]:
tensor=tf.constant([[1,2], [3,4]])
tensor

<tf.Tensor: id=20, shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]], dtype=int32)>

In [27]:
tensor + 2

<tf.Tensor: id=25, shape=(2, 2), dtype=int32, numpy=
array([[3, 4],
       [5, 6]], dtype=int32)>

In [28]:
tensor * 5

<tf.Tensor: id=27, shape=(2, 2), dtype=int32, numpy=
array([[ 5, 10],
       [15, 20]], dtype=int32)>

In [29]:
np.square(tensor)

array([[ 1,  4],
       [ 9, 16]], dtype=int32)

In [30]:
np.sqrt(tensor)

array([[1.        , 1.41421356],
       [1.73205081, 2.        ]])

In [35]:
np.dot(tensor, tensor_20)

array([[ 87, 106],
       [197, 216]], dtype=int32)

In [0]:
tf_string=tf.constant("Tensorflow")

In [37]:
tf_string

<tf.Tensor: id=29, shape=(), dtype=string, numpy=b'Tensorflow'>

string length

In [38]:
tf.strings.length(tf_string)

<tf.Tensor: id=30, shape=(), dtype=int32, numpy=10>

decoding a string in 'UTF8'

In [39]:
tf.strings.unicode_decode(tf_string, 'UTF8')

<tf.Tensor: id=34, shape=(10,), dtype=int32, numpy=array([ 84, 101, 110, 115, 111, 114, 102, 108, 111, 119], dtype=int32)>

# Storing arrays of strings

In [0]:
tf_string_array=tf.constant(["tensorflow","deep learning","AI"])

In [42]:
#iterating through the tf string array
for string in tf_string_array:
  print(string)

tf.Tensor(b'tensorflow', shape=(), dtype=string)
tf.Tensor(b'deep learning', shape=(), dtype=string)
tf.Tensor(b'AI', shape=(), dtype=string)
